config:
  version-candidate: VERSION
  dependencies:
    graql: [build]
    behaviour: [release]
    common: [build]

build:
  quality:
    dependency-analysis:
      image: graknlabs-ubuntu-20.04
      type: foreground
      command: |
        export GRABL_URL=https://vladyslav.eu.ngrok.io
        bazel run @graknlabs_dependencies//grabl/analysis:dependency-analysis

